### ISSUE TITLE
docker compose up error

### ISSUE THREAD

**Issue by chakkritte** [AeonPocket/web-wallet#2]
Dear AeonPocket

I try run your code  and it have error 

I use file (docker-compose.dev.yml)

```
 Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18
webwallet_php-wallet_1 exited with code 255
```

![image](https://user-images.githubusercontent.com/9056121/35556921-335a6588-05d6-11e8-827a-42591a76920a.png)

How to run web-wallet without error?

thank you.

**Comment by pushkar8723** [comment]
There is a seprate compose file for dev. Try:

```
docker-compose -f docker-compose.dev.yml up
```

**Comment by pushkar8723** [comment]
We mount our local file system during development and since required files are not installed locally on your system it is giving that error.
You can comment out line no  51 in docker compose file and directly use the pre-build image.

OR

you can install required dependencies using

```
cd src 
composer install && npm install
```

and then run the docker compose file.

**Comment by chakkritte** [comment]
@pushkar8723 I fixed.

thank you very much.
